version: '2'
services:
  redis-cluster:
    container_name: my_redis_cluster
    mem_limit: 50m
    build:
      context: .
      args:
        redis_version: '6.2.1'
    ports:
      - '7000-7005:7000-7005'
      - '5000-5010:5000-5010'